import Accordion from "react-bootstrap/Accordion"
import Badge from "react-bootstrap/Badge"
import Image from "react-bootstrap/Image"

function Home() {
    return (
        <div className="bg-secondary p-3">
            <h1 className="d-flex justify-content-center pt-3 fw-bold">
                LIGA PETICE <Badge bg="secondary">New</Badge>
            </h1>
            <Image src="https://1.bp.blogspot.com/-YvkrP-QOuFo/XXZP3P1xUCI/AAAAAAAAV_c/w0YNvUkjbdIXGjMZZY68WGwxjPZlZFz-QCLcBGAs/w1200-h630-p-k-no-nu/liga%2Bpetice.jpg" className="w-100 py-3" />;
            <Accordion defaultActiveKey="0" className="mb-5">
                <Accordion.Item eventKey="0" className="bg-secondary">
                    <Accordion.Header>Premier Leauge</Accordion.Header>
                    <Accordion.Body className="text-white">
                        The Premier League (also called EPL; legal name: The Football Association Premier League Limited) is the highest level of the English football league system. Contested by 20 clubs, it operates on a system of promotion and relegation with the English Football League (EFL). Seasons typically run from August to May with each team playing 38 matches against all other teams both home and away. Most games are played on Saturday and Sunday afternoons, with occasional weekday evening fixtures.
                        The competition was founded as the FA Premier League on 20 February 1992 following the decision of First Division (top-tier league from 1888 until 1992) clubs to break away from the English Football League. However, teams may still be relegated into and promoted from the EFL Championship. The Premier League takes advantage of a lucrative television rights sale to Sky: from 2019 to 2020, accumulated television rights were worth around £3.1 billion a year, with Sky and BT Group securing the domestic rights to broadcast 128 and 32 games respectively. The Premier League is a corporation where chief executive Richard Masters is responsible for its management, with member clubs acting as shareholders. Clubs were apportioned central payment revenues of £2.4 billion in 2016–17, with a further £343 million in solidarity payments to EFL clubs.
                        The Premier League is the most-watched sports league in the world, broadcast in 212 territories to 643 million homes and a potential TV audience of 4.7 billion people. For the 2018–19 season, the average Premier League match attendance was at 38,181, second to the German Bundesliga's 43,500, while aggregated attendance across all matches was the highest of any association football league at 14,508,981, and most stadium occupancies are near capacity. As of 2023, the Premier League is ranked first in the UEFA coefficient rankings based on performances in European competitions over the past five seasons, ahead of Spain's La Liga. Combined with the old First Division, the English top-flight has produced the second-highest number of European Cup / UEFA Champions League titles, with a record six English clubs having won fifteen European championships in total.
                        Fifty-one clubs have competed since the inception of the Premier League in 1992: forty-nine English and two Welsh clubs. Seven of them have won the title: Manchester United, Manchester City, Chelsea, Arsenal, Blackburn Rovers, Leicester City and Liverpool. Only six clubs have avoided relegation since its inception: Arsenal, Chelsea, Everton, Liverpool, Manchester United and Tottenham.
                    </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="1" className="bg-secondary">
                    <Accordion.Header>Bundesliga</Accordion.Header>
                    <Accordion.Body className="text-white">
                        The Bundesliga, sometimes referred to as the Fußball-Bundesliga or 1. Bundesliga, is a professional association football league in Germany. At the top of the German football league system, the Bundesliga is Germany's primary football competition. The Bundesliga comprises 18 teams and operates on a system of promotion and relegation with the 2. Bundesliga. Seasons run from August to May. Games are played on Fridays, Saturdays and Sundays. All of the Bundesliga clubs take part in the DFB-Pokal cup competition. The winner of the Bundesliga qualifies for the DFL-Supercup.
                        Fifty-six clubs have competed in the Bundesliga since its founding. Bayern Munich has won 32 of 60 titles, as well as the last eleven seasons, which is a European record. The Bundesliga has also seen other champions, with Borussia Dortmund, Hamburger SV, Werder Bremen, Borussia Mönchengladbach, and VfB Stuttgart most prominent among them. The Bundesliga is one of the top national leagues, ranked third in Europe according to UEFA's league coefficient ranking for the current 2022–23 season, based on performances in European competitions over the past five seasons. The Bundesliga led the UEFA ranking from 1976 to 1984 and in 1990. It has also produced the continent's top-rated club seven times. Bundesliga clubs have won eight UEFA Champions League, seven UEFA Europa League, four European Cup Winners' Cup, two UEFA Super Cup, two FIFA Club World Cup, and three Intercontinental Cup titles. Its players have accumulated nine Ballon d'Or awards, two The Best FIFA Men's Player awards, four European Golden Shoe, and three UEFA Men's Player of the Year awards including UEFA Club Footballer of the Year.
                        The Bundesliga is the number one association football league in the world in terms of average attendance; out of all sports, its average of 45,134 fans per game during the 2011–12 season was the second-highest of any sports league in the world after the American National Football League. The Bundesliga is broadcast on television in over 200 countries.
                        The Bundesliga was founded in 1962 in Dortmund and the first season started in 1963–64. The structure and organisation of the Bundesliga, along with Germany's other football leagues, have undergone frequent changes. The Bundesliga was founded by the Deutscher Fußball-Bund (English: German Football Association), but is now operated by the Deutsche Fußball Liga (English: German Football League).
                    </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="2" className="bg-secondary">
                    <Accordion.Header>La Liga</Accordion.Header>
                    <Accordion.Body className="text-white">
                        The Campeonato Nacional de Liga de Primera División, commonly known simply as Primera División in Spain and as La Liga in English-speaking countries. La Liga is the men's top professional football division of the Spanish football league system. Administered by the Liga Nacional de Fútbol Profesional,it is contested by 20 teams, with the three lowest-placed teams at the end of each season being relegated to the La Liga 2 and replaced by the top two teams and a play-off winner in that division.
                        Since its inception, a total of 62 teams have competed in La Liga. Nine teams have been crowned champions, with Barcelona winning the inaugural La Liga and Real Madrid winning the title a record 35 times. Barcelona are the most recent winners, having won the 2022–23 edition. During the 1940s Valencia, Atlético Madrid and Barcelona emerged as the strongest clubs, winning several titles. Real Madrid and Barcelona dominated the championship in the 1950s, each winning four La Liga titles during the decade. During the 1960s and 1970s, Real Madrid dominated La Liga, winning fourteen titles, with Atlético Madrid winning four.During the 1980s and 1990s Real Madrid were prominent in La Liga, but the Basque clubs of Athletic Club and Real Sociedad had their share of success, each winning two Liga titles. From the 1990s onward, Barcelona have dominated La Liga, winning sixteen titles to date.[5] Although Real Madrid has been prominent, winning ten titles, La Liga has also seen other champions, including Atlético Madrid, Valencia, and Deportivo La Coruña.
                        According to UEFA's league coefficient rankings, La Liga has been the top league in Europe in each of the seven years from 2013 to 2019 and has led Europe for 22 of the 60 ranked years up to 2019, more than any other country. It has also produced the continent's top-rated club more times than any other league in that period, more than double that of second-placed Serie A, including the top club in 10 of the 11 seasons between 2009 and 2019; each of these pinnacles was achieved by either Barcelona or Real Madrid. La Liga clubs have won the most UEFA Champions League , UEFA Europa League, UEFA Super Cup and FIFA Club World Cup titles, and its players have accumulated the highest number of Ballon d'Or awards, The Best FIFA Men's Player awards and UEFA Men's Player of the Year awards.
                        La Liga is one of the most popular professional sports leagues globally, with an average attendance of 26,933 for league matches in the 2018–19 season. This is the eighth-highest of any domestic professional sports league in the world and the third-highest of any professional association football league in the world, behind fellow big five leagues Bundesliga and Premier League, and above Serie A and Ligue 1.La Liga is also the seventh wealthiest professional sports league in the world by revenue, after the NFL, MLB, the NBA, the Premier League, the NHL, and the Bundesliga.
                    </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="3" className="bg-secondary">
                    <Accordion.Header>Ligue 1</Accordion.Header>
                    <Accordion.Body className="text-white">
                        Ligue 1, officially known as Ligue 1 Uber Eats for sponsorship reasons, is a French professional league for men's association football clubs. At top of the French football league system, it is the country's primary football competition. Administered by the Ligue de Football Professionnel, Ligue 1 is contested by 18 clubs (as of the 2023–24 season) and operates on a system of promotion and relegation from and to Ligue 2.
                        Seasons run from August to May. Clubs play two matches against each of the other teams in the league – one home and one away – totalling to 34 matches over the course of the season. Most games are played on Saturdays and Sundays, with a few games played during weekday evenings. Play is regularly suspended the last weekend before Christmas for two weeks before returning in the second week of January. As of 2021, Ligue 1 is one of the top national leagues, ranked fifth in Europe, behind England's Premier League, Spain's La Liga, Italy's Serie A, and Germany's Bundesliga.
                        Ligue 1 was inaugurated on 11 September 1932 under the name National before switching to Division 1 after a year of existence. It continued to operate under that name until 2002, when it adopted its current name. Paris Saint-Germain are the most successful clubs with eleven league titles, while Olympique Lyonnais is the club that has won the most consecutive titles (seven between 2002 and 2008). AS Saint-Étienne was the first club with ten titles. With the presence of 71 seasons in Ligue 1, Olympique de Marseille hold the record for most seasons among the elite, while Paris Saint-Germain hold the league record for longevity with 47 consecutive seasons (from 1974 to present). FC Nantes is the team with the longest consecutive unbeaten streak (32 matches) and the fewest number of defeats (one match) in a single season, doing so in the 1994–95 campaign. In addition, Nantes also holds the record for the longest time without losing at home, with a run of 92 matches from May 1976 to April 1981.
                        The current champions are Paris Saint-Germain, who won a record 11th title in the 2022–23 season. The league has been won on multiple occasions by foreign-based club AS Monaco, the presence of which within the league makes it a cross-border competition.
                        Ahead of the 2023–24 season, the number of teams in the league will be reduced to 18; four teams in the 2022–23 Ligue 1 will be relegated to Ligue 2 and only two teams in Ligue 2 will be promoted to Ligue 1.
                    </Accordion.Body>
                </Accordion.Item>
                <Accordion.Item eventKey="4" className="bg-secondary">
                    <Accordion.Header>Seria A</Accordion.Header>
                    <Accordion.Body className="text-white">
                        Serie A , također poznato i pod nazivom Serie A TIM zbog potpisanog sponzorskog ugovora s operaterom Telecom Italia profesionalno je ligaško nogometno prvenstvo u kojem se natječe dvadeset najboljih talijanskih nogometnih klubova, a koje je službeno osnovano prije više od 80 godina (točnije u sezoni 1929./30.). Sve do 2010. godine službeni naziv natjecanja bio je Lega Calcio, ali je u sezoni 2010./11. ime promijenjeno u Lega Serie A. Liga Serie A smatra se jednom od najboljih nogometnih liga na svijetu. Tijekom 1990-ih godina, Serie A bila je najbolja liga na svijetu iz koje je potekao najveći broj finalista europskih klupskih natjecanja: razni klubovi iz Italije rekordnih dvadeset i šest puta došli su do finala Lige prvaka, a naslov su osvajali dvanaest puta.Prema trenutačnom UEFA-inom ligaškom koeficijentu koji se izračunava na temelju uspjeha nogometnih klubova u domaćim prvenstvima i europskim natjecanjima, Serie A nalazi se na četvrtom mjestu najjačih europskih nogometnih liga, odmah iza španjolske, engleske i njemačke lige.
                        Talijansko nogometno prvenstvo svoj je trenutni format ligaškog natjecanja promijenio od sezone 1929./30. Do tada su se natjecanja odvijala po regionalnom i međuregionalnom sistemu. Prvenstva osvojena prije 1929. godine službeno su priznata i imaju jednaku "težinu" kao i ona osvojena nakon te godine. Jedina iznimka kada sezona nije igrana po standardnom ligaškom sistemu je ona iz 1945./46. kada je liga igrana u dvije geografske skupine zbog razorenih područja nakon Drugog svjetskog rata, ali se njezina titula službeno priznaje.
                        U talijanskoj ligi natječu se tri najpoznatija nogometna kluba na svijetu: Internazionale, Milan i Juventus. Sva tri kluba članovi su osnivači G-14, grupe koja predstavlja najveće i najprestižnije europske nogometne klubove; Serie A jedina je liga iz koje potječu čak tri kluba osnivača i člana skupine G-14. Više igrača osvojilo je nagradu Zlatna lopta dok su igrali u nekom klubu u Serie A nego u bilo kojoj drugoj ligi svijeta. Milan je drugi najuspješniji klub na svijetu po broju osvojenih međunarodnih nogometnih trofeja. Juventus je najuspješniji talijanski nogometni klub 20-og stoljeća te klub s najviše osvojenih trofeja Serie A do danas (34).To je jedini klub na svijetu koji je tijekom svog postojanja osvojio sve trofeje nogometnih kontinentalnih kupova te titulu klupskog prvaka svijeta. U sezoni 2009./10. Internazionale je postao prvi talijanski klub u povijesti koji je iste sezone osvojio trostruku krunu (Serie A, talijanski kup i Ligu prvaka), a također je i jedini klub u kompletnom natjecanju koji je od svog osnivanja do danas konstantno igrao u Serie A.
                    </Accordion.Body>
                </Accordion.Item>
            </Accordion>
        </div >
    )
}

export default Home
